package usercommands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/GoMudEngine/GoMud/internal/fileloader"
	"github.com/GoMudEngine/GoMud/internal/movenarration"
	"github.com/GoMudEngine/GoMud/internal/narration"
)

// TestMigratedWordingIsByteIdentical is the messaging-M4e1b byte-identity
// net, extending the mobcommands twin
// (internal/mobcommands/special_move_net_test.go) to the twelve player-side
// special-move files (internal/usercommands/{bash,drain,gore,kick,maul,
// pounce,rake,throttle,trip,grapple,shoot,throw}.go).
//
// It proves that the shipped special-move narration store
// (_datafiles/world/dogmud/narration/special-moves/*.yaml) renders EXACTLY
// the text these still-unmigrated Go files render today via fmt.Sprintf, at
// EVERY entry of EVERY variant pool -- not just index 0. A pool entry that
// only gets checked at index 0 cannot catch a divergence at index 5, which is
// the whole reason this net exists rather than a handful of spot checks.
//
// The fixture (testdata/pre_migration_literals.json) is generated by
// tools/move_narration_net.py, which extracts every format string and its
// argument list FRESH from the current Go source -- never hand-copied -- and
// is itself self-verifying: a pooled verb's fixture rows are cross-checked
// against a fresh, in-order scan of that file's []string{} pool
// declarations, and an unpooled verb's rows are matched by exact text against
// a fresh scan of every backtick literal in that file. Re-run that script any
// time the fixture needs to be regenerated; nothing here does.
//
// This must run against the UNMIGRATED tree: internal/usercommands/*.go
// still hold their Go literals (a later task migrates them), and this test
// reads them only through the frozen fixture, never the .go files directly.
//
// UNLIKE THE MOBCOMMANDS NET, MOST ROWS HERE SKIP RATHER THAN COMPARE, AND
// THAT IS EXPECTED. The store's `actor` role -- the player's own personal
// line, which a mob never had a client to receive -- is empty on every
// event the twelve player files touch, and the pools that ARE populated
// (actee/observer/remote_observer) are not yet squared to the player's
// pool lengths. A row whose event has not been authored yet is not a
// mismatch to report; it is a to-do item to skip cleanly, count, and leave
// for the migration to burn down. See skipReason below for exactly what
// gates a skip, and TestMigratedWordingIsByteIdentical's own t.Logf for the
// running count.
func TestMigratedWordingIsByteIdentical(t *testing.T) {
	rows := loadPreMigrationLiterals(t)
	if len(rows) == 0 {
		t.Fatal("fixture is empty; a net that checks nothing cannot fail")
	}

	groups := loadShippedMoveStore(t)
	tokens := standInTokens()

	skipped := 0
	checked := 0

	for _, row := range rows {
		row := row
		name := fmt.Sprintf("%s/%s/%s/%d", row.Verb, row.Event, row.Role, row.Index)
		t.Run(name, func(t *testing.T) {
			g := groups[row.Verb]
			if g == nil {
				skipped++
				t.Skipf("store has no %s.yaml yet", row.Verb)
			}

			v, ok := g.Variants(movenarration.EventKey(row.Event))
			if !ok {
				skipped++
				t.Skipf("store has no event %q for verb %q yet", row.Event, row.Verb)
			}

			// The actor role is the player's own personal line, which the
			// mob-only migration (PR 1a) never authored for any event: a mob
			// has no client to receive it. Its presence is this net's proxy
			// for "this event's pools have been squared for the player
			// side" -- until the actor line lands, the actee/observer/
			// remote_observer pools are not yet at the player's pool
			// lengths either, so a real comparison at THIS row's index would
			// either compare against the wrong entry (a short pool wrapping
			// via modulo) or fail on a squaring gap that is a to-do item,
			// not a wording regression. Gating on it, rather than on the
			// row's own role, means an actee/observer/remote_observer row
			// skips too, exactly when it should.
			if len(v.Actor) == 0 {
				skipped++
				t.Skipf("actor line(s) not yet authored for %s/%s; pools not yet squared", row.Verb, row.Event)
			}

			checked++

			// DefaultPicker, not FirstPicker: the trailing index override is
			// what makes checking a specific pool entry possible (see
			// narration.Render's own doc comment), and using the production
			// picker here rather than a picker that never draws keeps this
			// net's render call shaped exactly like a real call site's.
			roles := narration.Render(v, tokens, narration.DefaultPicker, row.Index)
			got := roleText(roles, row.Role)
			if got == "" {
				t.Fatalf("role %q rendered empty for %s/%s at index %d; the shipped event has no text for this role at this index", row.Role, row.Verb, row.Event, row.Index)
			}

			args := standInArgs(t, row.Args)
			want := fmt.Sprintf(row.Format, args...)

			if got != want {
				t.Errorf("wording moved:\n got  %q\n want %q", got, want)
			}
		})
	}

	t.Logf("%d/%d rows skipped pending later-task authoring (store not yet squared); %d checked", skipped, len(rows), checked)
}

// preMigrationLiteral is one row of the fixture: one Go format string, its
// original fmt.Sprintf argument order (spelled as canonical token names, see
// tools/move_narration_net.py's module docstring), which shipped YAML
// event/role it must eventually render identically to, and which entry of
// that event's variant pool it corresponds to.
type preMigrationLiteral struct {
	Verb   string   `json:"verb"`
	Event  string   `json:"event"`
	Role   string   `json:"role"`
	Index  int      `json:"index"`
	Format string   `json:"format"`
	Args   []string `json:"args"`
}

// loadPreMigrationLiterals reads the fixture relative to THIS test file's own
// path (runtime.Caller(0)), not the process CWD: this repo builds tests such
// that a relative path is not reliably the package directory.
func loadPreMigrationLiterals(t *testing.T) []preMigrationLiteral {
	t.Helper()

	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed; cannot locate the fixture")
	}
	path := filepath.Join(filepath.Dir(thisFile), "testdata", "pre_migration_literals.json")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var rows []preMigrationLiteral
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	return rows
}

// loadShippedMoveStore loads the special-move narration store straight from
// the shipped world tree, the same way the mobcommands twin does and for the
// same reason: a test binary never reads config.yaml, so
// movenarration.LoadMoveNarrationFiles (which resolves its directory through
// configs.GetFilePathsConfig) would silently resolve to the vestigial default
// world instead of dogmud. Reading the shipped path directly, relative to
// this test file via runtime.Caller(0), sidesteps both the config gap and the
// CWD gap.
func loadShippedMoveStore(t *testing.T) map[string]*movenarration.MoveNarrationGroup {
	t.Helper()

	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed; cannot locate the shipped store")
	}
	dir := filepath.Join(filepath.Dir(thisFile), "..", "..", "_datafiles", "world", "dogmud", "narration", "special-moves")

	groups, err := fileloader.LoadAllFlatFiles[string, *movenarration.MoveNarrationGroup](dir)
	if err != nil {
		t.Fatalf("loading %s: %v", dir, err)
	}
	if len(groups) == 0 {
		t.Fatalf("no special-move files loaded from %s", dir)
	}
	return groups
}

// roleText picks one audience's rendered line out of a narration.Roles by the
// fixture's role string, which spells the same four roles
// internal/movenarration's YAML tags use.
func roleText(r narration.Roles, role string) string {
	switch role {
	case "actor":
		return r.Actor
	case "actee":
		return r.Actee
	case "observer":
		return r.Observer
	case "remote_observer":
		return r.ActeeObserver
	}
	return ""
}

// Stand-in values for the store's token vocabulary. Each is distinctive
// enough that a swapped token (e.g. {actor} landing where {actee} belongs)
// changes the rendered string rather than accidentally matching.
//
// actor/actee each have a BARE and a TAGGED form because this codebase
// produces the same visual (a colour-tagged name) two different ways: most
// of the twelve files wrap a bare name inline in the format string
// (`<ansi fg="mobname">%s</ansi>`, arg is a bare name); shoot.go instead
// pre-builds a tagged span once and substitutes it with a bare %s and no
// further wrap. See tools/move_narration_net.py's module docstring for the
// full token vocabulary, including this file's two additions (heal, item).
const (
	standInActorBare   = "ACTORNAME"
	standInActorTagged = `<ansi fg="username">ACTORNAME</ansi>`
	standInActeeBare   = "ACTEENAME"
	standInActeeTagged = `<ansi fg="mobname">ACTEENAME</ansi>`
	standInDamage      = "DAMAGEDESC"
	standInHeal        = "HEALDESC"
	standInLabel       = "LABELTEXT"
	standInVerb        = "VERBTEXT"
	standInWith        = "WITHTEXT"
	standInWeapon      = `<ansi fg="itemname">WEAPONTEXT</ansi>`
	standInExitName    = "EXITDIR"
	standInPosition    = "POSITIONDESC"
	standInItem        = "ITEMNAME"
)

// standInTokens is the token map fed to narration.Render for the YAML side of
// the comparison ("got").
//
// The actor/actee tag colours are swapped from the mobcommands twin's
// (username for actor, mobname for actee) because the player IS the actor
// here: a player's own name renders as username, and their mob target's name
// renders as mobname -- the reverse of the mob-side net, where the mob is
// the actor and the player target is the actee.
func standInTokens() map[string]string {
	return map[string]string{
		narration.TokenActor:        standInActorTagged,
		narration.TokenActorPlain:   standInActorBare,
		narration.TokenActee:        standInActeeTagged,
		narration.TokenActeePlain:   standInActeeBare,
		movenarration.TokenDamage:   standInDamage,
		movenarration.TokenLabel:    standInLabel,
		movenarration.TokenVerb:     standInVerb,
		movenarration.TokenWith:     standInWith,
		movenarration.TokenWeapon:   standInWeapon,
		movenarration.TokenExitName: standInExitName,
		movenarration.TokenPosition: standInPosition,
	}
}

// argStandins maps each canonical token name the fixture's "args" lists use
// to the concrete value fmt.Sprintf receives, mirroring exactly what the
// original Go call site passed (bare name, pre-tagged name, or a plain
// word), never what the YAML token happens to expect.
//
// "heal" and "item" have no YAML-side token yet (drain's lifesteal detail
// line and throw's item name have no home in the shipped store today); they
// are defined here so a fixture row naming them can still be converted to a
// concrete fmt.Sprintf argument list on the "want" side once a later task
// gives them one, without a hidden "unknown arg token" surprise landing only
// then.
var argStandins = map[string]string{
	"actor":        standInActorBare,
	"actor_tagged": standInActorTagged,
	"actee":        standInActeeBare,
	"actee_tagged": standInActeeTagged,
	"damage":       standInDamage,
	"heal":         standInHeal,
	"label":        standInLabel,
	"verb":         standInVerb,
	"with":         standInWith,
	"weapon":       standInWeapon,
	"exitname":     standInExitName,
	"position":     standInPosition,
	"item":         standInItem,
}

// standInArgs converts a fixture row's token-name arg list into the
// interface{} slice fmt.Sprintf wants, in the ORIGINAL Go argument order.
func standInArgs(t *testing.T, names []string) []interface{} {
	t.Helper()

	out := make([]interface{}, 0, len(names))
	for _, n := range names {
		v, ok := argStandins[n]
		if !ok {
			t.Fatalf("fixture names unknown arg token %q; add it to argStandins", n)
		}
		out = append(out, v)
	}
	return out
}
