package mobcommands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/GoMudEngine/GoMud/internal/fileloader"
	"github.com/GoMudEngine/GoMud/internal/movenarration"
	"github.com/GoMudEngine/GoMud/internal/narration"
)

// TestMigratedWordingIsByteIdentical is the messaging-M4e1 byte-identity net.
//
// It proves that _datafiles/world/dogmud/narration/special-moves/*.yaml, the
// wording the mob special-move files (internal/mobcommands/{kick,bash,...}.go)
// will read from once Task 8 migrates them, renders EXACTLY the text those
// still-unmigrated Go files render today via fmt.Sprintf. Tokens sit where the
// old %s arguments sat, and no wording moved, or this test names the
// verb/event/role where it did.
//
// The fixture (testdata/pre_migration_literals.json) is generated by
// tools/move_narration_net.py, which extracts each format string and its
// argument list FRESH from the current Go source by regex -- not hand-copied
// -- and cross-checks that against
// docs/superpowers/audits/2026-09-21-m4e1-site-inventory.md's own per-literal
// table. Re-run that script any time the fixture needs to be regenerated;
// nothing here does.
//
// This must run against the UNMIGRATED tree: internal/mobcommands/*.go still
// hold their Go literals (Task 8 migrates them later), and this test reads
// them only through the frozen fixture, never the .go files directly.
//
// AS OF THIS COMMIT, SEVEN SUBTESTS ARE RED ON PURPOSE. This is the net
// doing its job: it found two real content defects in the shipped
// special-moves YAML (Task 3's authoring), and per the task that built this
// net, a genuine mismatch gets reported, not silently fixed here or dropped
// from the fixture.
//
//  1. bash/{knockdown,hit,partial}/actee and bash/knockdown/observer (4
//     subtests): bash.go's four knockdown/hit/partial lines wrap the
//     species-varying label in <ansi fg="yellow-bold">
//     (bash.go:77,86,92,108); bash.yaml's {label} token is never wrapped, so
//     migrating today would silently drop the highlight from those four
//     lines.
//  2. shoot/{hit,partial,miss}/actee (3 subtests): shoot.go:84 sets
//     `shooter := mobName`, and mobName (shoot.go:49) is built
//     PRE-TAGGED (`<ansi fg="mobname">%s</ansi>`), not bare -- unlike every
//     other file's mobName. shoot.yaml's hit/partial/miss events use
//     {actor_plain} for this slot, which renders bare. The implementation
//     plan (2026-09-21-messaging-m4e1-mob-special-moves.md, ~line 945)
//     asserts shooter is bare and that is why {actor_plain} was chosen; the
//     source does not support that claim.
//
// Both are pre-migration content bugs for a human to resolve (fix the two
// YAML files, or the plan's shoot.go guidance) before Task 8 migrates these
// call sites -- not defects in this test or its fixture.
func TestMigratedWordingIsByteIdentical(t *testing.T) {
	rows := loadPreMigrationLiterals(t)
	if len(rows) == 0 {
		t.Fatal("fixture is empty; a net that checks nothing cannot fail")
	}

	groups := loadShippedMoveStore(t)
	tokens := standInTokens()

	for _, row := range rows {
		t.Run(row.Verb+"/"+row.Event+"/"+row.Role, func(t *testing.T) {
			g := groups[row.Verb]
			if g == nil {
				t.Fatalf("verb %q absent from the shipped store", row.Verb)
			}
			v, ok := g.Variants(movenarration.EventKey(row.Event))
			if !ok {
				t.Fatalf("verb %q has no event %q in the shipped store", row.Verb, row.Event)
			}

			roles := narration.Render(v, tokens, narration.FirstPicker)
			got := roleText(roles, row.Role)
			if got == "" {
				t.Fatalf("role %q rendered empty for %s/%s; the shipped event has no text for this role", row.Role, row.Verb, row.Event)
			}

			args := standInArgs(t, row.Args)
			want := fmt.Sprintf(row.Format, args...)

			if got != want {
				t.Errorf("wording moved:\n got  %q\n want %q", got, want)
			}
		})
	}
}

// preMigrationLiteral is one row of the fixture: one Go format string, its
// original fmt.Sprintf argument order (spelled as canonical token names, see
// tools/move_narration_net.py's module docstring), and which shipped YAML
// event/role it must render identically to.
type preMigrationLiteral struct {
	Verb   string   `json:"verb"`
	Event  string   `json:"event"`
	Role   string   `json:"role"`
	Format string   `json:"format"`
	Args   []string `json:"args"`
}

// loadPreMigrationLiterals reads the fixture relative to THIS test file's own
// path (runtime.Caller(0)), not the process CWD: this repo builds tests such
// that a relative path is not reliably the package directory.
func loadPreMigrationLiterals(t *testing.T) []preMigrationLiteral {
	t.Helper()

	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed; cannot locate the fixture")
	}
	path := filepath.Join(filepath.Dir(thisFile), "testdata", "pre_migration_literals.json")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var rows []preMigrationLiteral
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	return rows
}

// loadShippedMoveStore loads the special-move narration store straight from
// the shipped world tree, the same way shipped_narration_data_guard_test.go's
// "special-moves" subtest does, and for the same reason: a test binary never
// reads config.yaml, so movenarration.LoadMoveNarrationFiles (which resolves
// its directory through configs.GetFilePathsConfig) would silently resolve to
// the vestigial default world instead of dogmud. Reading the shipped path
// directly, relative to this test file via runtime.Caller(0), sidesteps both
// the config gap and the CWD gap.
func loadShippedMoveStore(t *testing.T) map[string]*movenarration.MoveNarrationGroup {
	t.Helper()

	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed; cannot locate the shipped store")
	}
	dir := filepath.Join(filepath.Dir(thisFile), "..", "..", "_datafiles", "world", "dogmud", "narration", "special-moves")

	groups, err := fileloader.LoadAllFlatFiles[string, *movenarration.MoveNarrationGroup](dir)
	if err != nil {
		t.Fatalf("loading %s: %v", dir, err)
	}
	if len(groups) == 0 {
		t.Fatalf("no special-move files loaded from %s", dir)
	}
	return groups
}

// roleText picks one audience's rendered line out of a narration.Roles by the
// fixture's role string, which spells the same four roles
// internal/movenarration's YAML tags use.
func roleText(r narration.Roles, role string) string {
	switch role {
	case "actor":
		return r.Actor
	case "actee":
		return r.Actee
	case "observer":
		return r.Observer
	case "remote_observer":
		return r.ActeeObserver
	}
	return ""
}

// Stand-in values for the store's token vocabulary. Each is distinctive
// enough that a swapped token (e.g. {actor} landing where {actee} belongs)
// changes the rendered string rather than accidentally matching.
//
// actor/actee each have a BARE and a TAGGED form because this codebase
// produces the same visual (a colour-tagged name) two different ways: most
// of the 13 files wrap a bare name inline in the format string
// (`<ansi fg="mobname">%s</ansi>`, arg is bare mob.Character.Name); shoot.go
// instead pre-builds a tagged span once (mobName :=
// fmt.Sprintf(`<ansi fg="mobname">%s</ansi>`, ...)) and substitutes it
// with a bare %s and no further wrap. The store's {actor}/{actee} tokens are
// always meant to receive an ALREADY-TAGGED value (no shipped YAML line
// wraps them in its own <ansi> tag), so standInTokens uses the tagged form
// for {actor}/{actee}, and standInArgs supplies whichever form the ORIGINAL
// Go call site actually passed to fmt.Sprintf: bare for the inline-wrap
// files, tagged for shoot.go (see tools/move_narration_net.py's
// SHOOT_ARG_TO_TOKEN and its "actor_tagged"/"actee_tagged" token names).
const (
	standInActorBare   = "ACTORNAME"
	standInActorTagged = `<ansi fg="mobname">ACTORNAME</ansi>`
	standInActeeBare   = "ACTEENAME"
	standInActeeTagged = `<ansi fg="username">ACTEENAME</ansi>`
	standInDamage      = "DAMAGEDESC"
	standInLabel       = "LABELTEXT"
	standInVerb        = "VERBTEXT"
	standInWith        = "WITHTEXT"
	standInWeapon      = `<ansi fg="itemname">WEAPONTEXT</ansi>`
	standInExitName    = "EXITDIR"
	standInPosition    = "POSITIONDESC"
)

// standInTokens is the token map fed to narration.Render for the YAML side of
// the comparison ("got"). {actor_plain} is included because shoot.yaml's
// hit/partial/miss events use it; whether that is CORRECT is exactly one of
// the things this net checks (see the shoot-specific note in
// tools/move_narration_net.py), not assumed here.
func standInTokens() map[string]string {
	return map[string]string{
		narration.TokenActor:        standInActorTagged,
		narration.TokenActorPlain:   standInActorBare,
		narration.TokenActee:        standInActeeTagged,
		narration.TokenActeePlain:   standInActeeBare,
		movenarration.TokenDamage:   standInDamage,
		movenarration.TokenLabel:    standInLabel,
		movenarration.TokenVerb:     standInVerb,
		movenarration.TokenWith:     standInWith,
		movenarration.TokenWeapon:   standInWeapon,
		movenarration.TokenExitName: standInExitName,
		movenarration.TokenPosition: standInPosition,
	}
}

// argStandins maps each canonical token name the fixture's "args" lists use
// to the concrete value fmt.Sprintf receives, mirroring exactly what the
// original Go call site passed (bare name, pre-tagged name, or a plain
// word), never what the YAML token happens to expect.
var argStandins = map[string]string{
	"actor":        standInActorBare,
	"actor_tagged": standInActorTagged,
	"actee":        standInActeeBare,
	"actee_tagged": standInActeeTagged,
	"damage":       standInDamage,
	"label":        standInLabel,
	"verb":         standInVerb,
	"with":         standInWith,
	"weapon":       standInWeapon,
	"exitname":     standInExitName,
	"position":     standInPosition,
}

// standInArgs converts a fixture row's token-name arg list into the
// interface{} slice fmt.Sprintf wants, in the ORIGINAL Go argument order.
func standInArgs(t *testing.T, names []string) []interface{} {
	t.Helper()

	out := make([]interface{}, 0, len(names))
	for _, n := range names {
		v, ok := argStandins[n]
		if !ok {
			t.Fatalf("fixture names unknown arg token %q; add it to argStandins", n)
		}
		out = append(out, v)
	}
	return out
}
